### ISSUE TITLE
TRACKER: Drake system dependencies in ROS

### ISSUE THREAD

**Issue by j-rivero** [RobotLocomotion/ros-drake-vendor#4]
The issue collects problems and issues for different system dependencies in Drake that are not available in the ROS buildfarm. Most of the times it is a problem of not having a rosdistro key available. 

Critical to build that are failing:

 * https://github.com/RobotLocomotion/ros-drake-vendor/issues/3
 * #2
 * `patchelf` not available in rosdistro. https://github.com/ros/rosdistro/pull/39435 
 * `lsb-release` not available in rosdistro, https://github.com/ros/rosdistro/pull/39768

Workarounds available:

 * `libglx-dev`: rosdistro seems not to have any key related to `libglx` or similar. The package is installed since it is a dependency of `qtbase5-dev`. Drake uses [<GL/glx.h>](https://github.com/RobotLocomotion/drake/blob/9ba8f5d8d4ee6919ec41542d47509549cfa8d919/geometry/render_gl/internal_opengl_context.cc#L13)

Not direct dependencies:

 * `libmumps-seq-dev`:  rosdistro seems not to have any key related to the `mumps` library or similar. The package is installed since it is a dependency of the `coinor-libipopt-dev`. Drake uses the [mumps linear_solver](https://github.com/RobotLocomotion/drake/blob/9ba8f5d8d4ee6919ec41542d47509549cfa8d919/solvers/ipopt_solver.cc#L771).

**Comment by jwnimmer-tri** [comment]
Re: mumps -- Drake builds IPOPT from source, which [uses MUMPS](https://github.com/RobotLocomotion/drake/blob/aac666e8490ee7e8c8a32dc3914d0e9d333419d2/tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel#L365).  Drake's own source code does not directly `#include` mumps headers, but the IPOPT source code we build does `#include` mumps headers.

**Comment by j-rivero** [comment]
Submitted `patchelf` to the rosdistro index patchelf https://github.com/ros/rosdistro/pull/39435

**Comment by j-rivero** [comment]
Found that `lsb-release` is not installed by default in the ROS buildfarm and it is used by the Drake buildsystem, sent it to rosdistro https://github.com/ros/rosdistro/pull/39768

**Comment by j-rivero** [comment]
> Found that `lsb-release` is not installed by default in the ROS buildfarm and it is used by the Drake buildsystem, sent it to rosdistro [ros/rosdistro#39768](https://github.com/ros/rosdistro/pull/39768)

Merged.

**Comment by jwnimmer-tri** [comment]
I'll close the "tracker".  To the extent we are missing rosdep keys, we can file separate issues for each one from now on.
